In [1]:
import numpy as np

In [2]:
arr = np.array([[1,3,4],[3,4,5]])

In [3]:
arr

array([[1, 3, 4],
       [3, 4, 5]])

In [4]:
arr[0][1]

3

In [5]:
for i in arr :
    print(i)
    for j in i :
        print(j)

[1 3 4]
1
3
4
[3 4 5]
3
4
5


In [6]:
arr = np.random.randint(0,500, size=30)
arr

array([248,  97,  73, 231, 207, 264,   0, 364,  44, 185, 314, 167, 414,
       171, 300, 445, 326,  97, 201, 407, 263, 239, 382, 459,  26,  71,
        43,   0, 146, 242])

In [7]:
arr = np.sort(arr)
arr

array([  0,   0,  26,  43,  44,  71,  73,  97,  97, 146, 167, 171, 185,
       201, 207, 231, 239, 242, 248, 263, 264, 300, 314, 326, 364, 382,
       407, 414, 445, 459])

In [9]:
arr = np.linspace(0,10,20)
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])