In [5]:
# Python program to demonstrate
# basic array characteristics
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [3]:
# import pandas as pd 
import pandas as pd  
      
# List1  
lst = [['Geek', 25], ['is', 30], 
       ['for', 26], ['Geeksforgeeks', 22]] 
  
# creating df object with columns specified    
df = pd.DataFrame(lst, columns =['Tag', 'number']) 
print(df )

             Tag  number
0           Geek      25
1             is      30
2            for      26
3  Geeksforgeeks      22


In [4]:
import numpy as np
arr1=np.array([[1,2],[4,5]])
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[[1 2]
 [4 5]]
(2, 2)
2


In [16]:
import numpy as np 
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.shape)
print(a.ndim)
print(a[0])

(2, 2, 2)
3
[[1 2]
 [3 4]]


In [17]:
import numpy as np 
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.shape)
print(a.ndim)
print(a[1])

(2, 2, 2)
3
[[5 6]
 [7 8]]


(2, 2, 2)
3
[3 4]


In [2]:
import numpy as np 
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.shape)
print(a.ndim)
print(a[0,1])

(2, 2, 2)
3
[3 4]


In [1]:
import numpy as np 
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.shape)
print(a.ndim)
print(a[0,0])

(2, 2, 2)
3
[1 2]


In [21]:
import numpy as np 
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.shape)
print(a.ndim)
print(a[0,0])

(2, 2, 2)
3
[1 2]


In [22]:
import numpy as np 
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.shape)
print(a.ndim)
print(a[0,0,0])

(2, 2, 2)
3
1


In [26]:
import numpy as np 
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.shape)
print(a.ndim)
print(a[1,1,0])

(2, 2, 2)
3
7


In [29]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6]]])
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
3
