Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.



In [2]:
import numpy as np

list = [1,2,3,4,5]

array_list = np.array(list)

print(type(list))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.



In [4]:
print("Data types of elements in list_:")
for item in list:
    print(type(item))

# Print data types of elements in the array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)


In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in the list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print data types of elements in the array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size




In [6]:
array_list.shape , array_list.size

((5,), 5)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]




In [7]:
import numpy as np

# Create a 3x3 matrix containing zeros
zero_matrix = np.zeros((3, 3))

print("Zero matrix:")
print(zero_matrix)


Zero matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.eye(5)

print("Identity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
